remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme

title: Marilia Garcia Portfolio
description: Frontend Developer Portfolio

# Custom configurations
author: Marilia Garcia
avatar: /assets/images/your-photo.jpg 
